# Generated by Django 5.1.2 on 2024-10-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
                ('year_fundacion', models.IntegerField()),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('imagen', models.ImageField(upload_to='empresas/')),
            ],
        ),
    ]
