# Generated by Django 5.1.2 on 2024-10-16 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('area', models.CharField(choices=[('puzzle', 'Puzzle'), ('estrategia', 'Estrategia'), ('aventura_logica', 'Aventura Lógica'), ('rpg', 'RPG'), ('simulacion', 'Simulación'), ('juegos_educativos', 'Juegos Educativos'), ('juegos_de_mesa', 'Juegos de Mesa'), ('rompecabezas', 'Rompecabezas'), ('juegos_interactivos', 'Juegos Interactivos'), ('otros', 'Otros')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.IntegerField(choices=[(15, '15%'), (0, '0%')])),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursales.sucursal')),
            ],
        ),
    ]
